Repository firebase/firebase-admin-dotnet, pull requests merged in 2020-10, with the labels that each got.

#261 [chore] Release 1.17.1
  FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Labels: release:publish, release:tweet

#263 feat(fcm): Support for sending up to 500 messages in a batch
  FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseMessagingSnippets.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MulticastMessageTest.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/MulticastMessage.cs
Labels: release-note

#251 change: Update project target frameworks and dependencies
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractFirebaseAuthTest.cs
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractOidcProviderConfigTest.cs
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractSamlProviderConfigTest.cs
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TenantManagerTest.cs
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAdmin.IntegrationTests.csproj
  FirebaseAdmin/FirebaseAdmin.IntegrationTests/IntegrationTestUtils.cs
  FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAdmin.Snippets.csproj
  FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAppSnippets.cs
  FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/FirebaseUserManagerTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj
  FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs
  FirebaseAdmin/FirebaseAdmin.Tests/Messaging/TopicManagementResponseTest.cs
  FirebaseAdmin/FirebaseAdmin/Auth/IUserInfo.cs
  FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs
  FirebaseAdmin/FirebaseAdmin/Auth/Jwt/HttpPublicKeySource.cs
  FirebaseAdmin/FirebaseAdmin/Auth/Jwt/PublicKey.cs
  FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
  FirebaseAdmin/FirebaseAdmin/FirebaseApp.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/ApnsConfig.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/BatchResponse.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/CriticalSound.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/MulticastMessage.cs
  FirebaseAdmin/FirebaseAdmin/Messaging/WebpushConfig.cs
  README.md
Labels: api: core, release-note
